// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOuDb2c8skYPyKn7pLNUhVaLXeRPTys6c',
    appId: '1:478989716555:web:3f67ec9bfd2dd6c2ee91ce',
    messagingSenderId: '478989716555',
    projectId: 'team-for-gamers-6be4d',
    authDomain: 'team-for-gamers-6be4d.firebaseapp.com',
    storageBucket: 'team-for-gamers-6be4d.firebasestorage.app',
    measurementId: 'G-1YH04PH93V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAirwjRlXEsjMmvRH3TZoC8e-mZMQ2cWEU',
    appId: '1:478989716555:android:e48fa435019e94a1ee91ce',
    messagingSenderId: '478989716555',
    projectId: 'team-for-gamers-6be4d',
    storageBucket: 'team-for-gamers-6be4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnCUdDHN4e5ASgGXE2C46LMsPsLKAg5lo',
    appId: '1:478989716555:ios:f40e8dbf521bb1b6ee91ce',
    messagingSenderId: '478989716555',
    projectId: 'team-for-gamers-6be4d',
    storageBucket: 'team-for-gamers-6be4d.firebasestorage.app',
    iosBundleId: 'com.teamforgamers.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.teamForGamers',
  );
}